Fix readme formatting issues
$ python setup.py check -r -s
running check
warning: check: Unexpected indentation. (line 63)

error: Please correct your package

Change-Id: I26057e9e2f86f092e04efd3f56f7d55be937f2de
Related-Bug: #1774001
(cherry picked from commit 51291f1460f6ada6039558c8231de82db0d6cb22)